int main()
{
        auto int a1 = 1;
        auto char a2 = 2;
        auto short a3 = 3;
        auto long a4 = 12;
        auto float a5 = 123;
        auto double a6 = 23;
        auto unsigned int a7 = 12;
        auto signed int a8 = 12354;
        auto long long a9 = 123;
        auto signed long a10 = 21;
        auto short int a11 = 121;
        auto long long int a12 = 1232;
        auto unsigned char a13 = 94;
        auto signed char a14 = 93;
        auto long long a15 = 232;
        auto signed long a16 = 1232;
        auto unsigned long a17 = 12;
        auto long double a20 = 12.21;
        auto signed short a23 = 142;
        auto unsigned short a24 = 1242;


        volatile int b1 = 1;
        volatile char b2 = 2;
        volatile short b3 = 3;
        volatile long b4 = 12;
        volatile float b5 = 123;
        volatile double b6 = 23;
        volatile unsigned int b7 = 12;
        volatile signed int b8 = 12354;
        volatile long long b9 = 123;
        volatile signed long b10 = 21;
        volatile short int b11 = 121;
        volatile long long int b12 = 1232;
        volatile unsigned char b13 = 94;
        volatile signed char b14 = 93;
        volatile long long b15 = 232;
        volatile signed long b16 = 1232;
        volatile unsigned long b17 = 12;
        volatile long double b20 = 12.21;
        volatile signed short b23 = 142;
        volatile unsigned short b24 = 1242;

        volatile static int c1 = 1;
        volatile static char c2 = 2;
        volatile static short c3 = 3;
        volatile static long c4 = 12;
        volatile static float c5 = 123;
        volatile static double c6 = 23;
        volatile static unsigned int c7 = 12;
        volatile static signed int c8 = 12354;
        volatile static long long c9 = 123;
        volatile static signed long c10 = 21;
        volatile static short int c11 = 121;
        volatile static long long int c12 = 1232;
        volatile static unsigned char c13 = 94;
        volatile static signed char c14 = 93;
        volatile static long long c15 = 232;
        volatile static signed long c16 = 1232;
        volatile static unsigned long c17 = 12;
        volatile static long double c20 = 12.21;
        volatile static signed short c23 = 142;
        volatile static unsigned short c24 = 1242;

        static int d1 = 1;
        static char d2 = 2;
        static short d3 = 3;
        static long d4 = 12;
        static float d5 = 123;
        static double d6 = 23;
        static unsigned int d7 = 12;
        static signed int d8 = 12354;
        static long long d9 = 123;
        static signed long d10 = 21;
        static short int d11 = 121;
        static long long int d12 = 1232;
        static unsigned char d13 = 94;
        static signed char d14 = 93;
        static long long d15 = 232;
        static signed long d16 = 1232;
        static unsigned long d17 = 12;
        static long double d18 = 12.21;
        static signed short d19 = 142;
        static unsigned short d20 = 1242;
        extern int e1 ;
        extern char e2 ;
        extern short e3 ;
        extern long e4 ;
        extern float e5 ;
        extern double e6 ;
        extern unsigned int e7 ;
        extern signed int e8 ;
        extern long long e9 ;
        extern signed long e10 ;
        extern short int e11 ;
        extern long long int e12 ;
        extern unsigned char e13 ;
        extern signed char e14 ;
        extern long long e15 ;
        extern signed long e16 ;
        extern unsigned long e17 ;
        extern long double e18 ;
        extern signed short e19 ;
        extern unsigned short e20 ;

        const extern int f1 ;
        const extern char f2 ;
        const extern short f3 ;
        const extern long f4 ;
        const extern float f5 ;
        const extern double f6 ;
        const extern unsigned int f7 ;
        const extern signed int f8 ;
        const extern long long f9 ;
        const extern signed long f10 ;
        const extern short int f11 ;
        const extern long long int f12 ;
        const extern unsigned char f13 ;
        const extern signed char f14 ;
        const extern long long f15 ;
        const extern signed long f16 ;
        const extern unsigned long f17 ;
        const extern long double f18 ;
        const extern signed short f19 ;
        const extern unsigned short f20 ;

        const int g1 ;
        const char g2 ;
        const short g3 ;
        const long g4 ;
        const float g5 ;
        const double g6 ;
        const unsigned int g7 ;
        const signed int g8 ;
        const long long g9 ;
        const signed long g10 ;
        const short int g11 ;
        const long long int g12 ;
        const unsigned char g13 ;
        const signed char g14 ;
        const long long g15 ;
        const signed long g16 ;
        const unsigned long g17 ;
        const long double g18 ;
        const signed short g19 ;
        const unsigned short g20;


        register int h1 ;
        register char h2 ;
        register short h3 ;
        register long h4 ;
        register float h5 ;
        register double h6 ;
        register unsigned int h7 ;
        register signed int h8 ;
        register long long h10 ;
        register signed long h11 ;
        register short int h12 ;
        register long long int h13 ;
        register unsigned char h14 ;
        register signed char h15 ;
        register long long h16 ;
        register signed long h17 ;
        register unsigned long h18 ;
        register long double h19 ;
        register signed short h20 ;
        register unsigned short h21;



         int g1 ;
         char g2 ;
         short g3 ;
         long g4 ;
         float g5 ;
         double g6 ;
         unsigned int g7 ;
         signed int g8 ;
         long long g9 ;
         signed long g10 ;
         short int g11 ;
         long long int g12 ;
         unsigned char g13 ;
         signed char g14 ;
         long long g15 ;
         signed long g16 ;
         unsigned long g17 ;
         long double g18 ;
         signed short g19 ;
         unsigned short g20;
        
        return 0;
}